### ISSUE TITLE
Negative lookahead doesn't work correctly

### ISSUE THREAD

**Issue by indiejames** [lpil/elixre#20]
![screen shot 2015-04-11 at 10 54 37 pm](https://cloud.githubusercontent.com/assets/308058/7104203/c4cced26-e09d-11e4-9137-b8254fc669bf.png)

**Comment by lpil** [comment]
Thanks :)

**Comment by lpil** [comment]
```elixir
Regex.run ~r/abc(?!.*abc)/, "abcghjkabchj", return: :index
```

**Comment by lpil** [comment]
There we go :)

**Comment by indiejames** [comment]
Nice, thanks. I didn't now about return: :index.

**Comment by lpil** [comment]
Me either ;)
