### ISSUE TITLE
http://www.elixre.uk/ is down

### ISSUE THREAD

**Issue by FreedomBen** [lpil/elixre#45]
Not sure if this is the best place, but http://www.elixre.uk/ is down.  Also tried https://www.elixre.uk/ (https).

If the sleep time that Heroku enforces is a problem (which it has been for some of my apps), you should take a look at https://gigalixir.com/ .

**Comment by lpil** [comment]
Hiya. Elixire now lives at http://elixre.lpil.uk, but I forgot to update the URL on this github page. Thanks for the report!
